# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 

createCohortDiagnosticsModuleSpecifications <- function(cohortIds = NULL,
                                                        runInclusionStatistics = TRUE,
                                                        runIncludedSourceConcepts = TRUE,
                                                        runOrphanConcepts = TRUE,
                                                        runTimeSeries = FALSE,
                                                        runVisitContext = TRUE,
                                                        runBreakdownIndexEvents = TRUE,
                                                        runIncidenceRate = TRUE,
                                                        runCohortRelationship = TRUE,
                                                        runTemporalCohortCharacterization = TRUE,
                                                        temporalCovariateSettings = CohortDiagnostics::getDefaultCovariateSettings(),
                                                        minCharacterizationMean = 0.01,
                                                        incremental = FALSE) {
  analysis <- list()
  for (name in names(formals(createCohortDiagnosticsModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortDiagnosticsModule",
                         version = "add-upload-callback-functionality",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortDiagnosticsModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
