
getDefaultCovariateSettings <- function() {
  covariateSettings <- '
{
  "temporal": true,
  "temporalSequence": false,
  "DemographicsGender": true,
  "DemographicsAge": true,
  "DemographicsAgeGroup": true,
  "DemographicsRace": true,
  "DemographicsEthnicity": true,
  "DemographicsIndexYear": true,
  "DemographicsIndexMonth": true,
  "DemographicsPriorObservationTime": true,
  "DemographicsPostObservationTime": true,
  "DemographicsTimeInCohort": true,
  "DemographicsIndexYearMonth": true,
  "ConditionOccurrence": true,
  "ConditionEraStart": true,
  "ConditionEraOverlap": true,
  "ConditionEraGroupOverlap": true,
  "DrugEraStart": true,
  "DrugEraGroupOverlap": true,
  "ProcedureOccurrence": true,
  "DeviceExposure": true,
  "Measurement": true,
  "Observation": true,
  "CharlsonIndex": true,
  "Dcsi": true,
  "Chads2": true,
  "Chads2Vasc": true,
  "temporalStartDays": [-9999, -365, -180, -30, -365, -30, 0, 1, 31, -9999],
  "temporalEndDays": [0, 0, 0, 0, -31, -1, 0, 30, 365, 9999],
  "includedCovariateConceptIds": [],
  "addDescendantsToInclude": false,
  "excludedCovariateConceptIds": [],
  "addDescendantsToExclude": false,
  "includedCovariateIds": [],
  "attr_class": "covariateSettings",
  "attr_fun": "getDbDefaultCovariateData"
}
  '
  ParallelLogger::convertJsonToSettings(covariateSettings)
}


# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 

createCohortDiagnosticsModuleSpecifications <- function(cohortIds = NULL,
                                                        runInclusionStatistics = TRUE,
                                                        runIncludedSourceConcepts = TRUE,
                                                        runOrphanConcepts = TRUE,
                                                        runTimeSeries = FALSE,
                                                        runVisitContext = TRUE,
                                                        runBreakdownIndexEvents = TRUE,
                                                        runIncidenceRate = TRUE,
                                                        runCohortRelationship = TRUE,
                                                        runTemporalCohortCharacterization = TRUE,
                                                        temporalCovariateSettings = getDefaultCovariateSettings(),
                                                        minCharacterizationMean = 0.01,
                                                        irWashoutPeriod = 0,
                                                        incremental = FALSE) {
  analysis <- list()
  for (name in names(formals(createCohortDiagnosticsModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortDiagnosticsModule",
                         version = "0.1.0",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortDiagnosticsModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
